### ISSUE TITLE
Is Family Sharing out of scope for this client or you have plans to implement it?

### ISSUE THREAD

**Issue by awsms** [OpenSteamClient/OpenSteamClient#28]

**Comment by Rosentti** [comment]
Family sharing is planned, but I have no idea how to do it (I haven't looked into it). Looks like something to do with IClientDeviceAuth.

**Comment by Rosentti** [comment]
Welp. This is now implemented (albeit without any special GUI). 
If you are in a family group, your games are available to be played. 
The legacy sharing system will not be supported.
