### ISSUE TITLE
doesnt launch on box64

### ISSUE THREAD

**Issue by Comy112** [OpenSteamClient/OpenSteamClient#30]
Hello. I tried to run opensteamclient on Termux (proot-distro) with box64, and it didnt launch. Do you know what could be the issue? I do this out of boredom to test out something.
![Screenshot_20230926_211934_TermuxX11](https://github.com/Rosentti/opensteamclient/assets/102830774/4e6593f3-2f4e-4fcd-9a6d-76c1636a8ddd)

**Comment by Rosentti** [comment]
You're missing libarchive, libprotobuf, libqrencode. They should be statically linked, but it seems like that didn't happen. You can try installing those packages.
