### ISSUE TITLE
steamui.so

### ISSUE THREAD

**Issue by MrDarcyA** [OpenSteamClient/OpenSteamClient#38]
I launched the client in my terminal and it printed out this error
"dlmopen steamui.so failed: steamui.so: cannot open shared object file: No such file or directory"
then seg faulted.

**Comment by MrDarcyA** [comment]
Arch Linux user BTW

**Comment by Rosentti** [comment]
It likes to segfault a bit. Try a couple more times.

**Comment by MrDarcyA** [comment]
after restoring the official steam client is there anything I do before using open one again?

**Comment by MrDarcyA** [comment]
still refuses to launch.
I haven't launched it successfully not even once.

**Comment by Rosentti** [comment]
Ah. You're probably using the latest release? It's currently broken, but there's a build artifact available to download that should work. I'll send the link.

**Comment by Rosentti** [comment]
https://github.com/OpenSteamClient/OpenSteamClient/actions/runs/7640025864/artifacts/1191594439

**Comment by Rosentti** [comment]
Also, seems like a duplicate of #37
