### ISSUE TITLE
Opensteam crashes when launched after have downloaded Steam stuff

### ISSUE THREAD

**Issue by Linerd4** [OpenSteamClient/OpenSteamClient#47]
Good day,
yesterday I fetched and compiled opensteam by using the AUR.
After the compilation and installation was completed, I launched the program from command line. It downloaded a bunch of stuff, but then crashed.
Since then, everytime I try to launch I get exactly the same error: I'll put here the output from the command line and the dump file generated.
[log.txt](https://github.com/OpenSteamClient/OpenSteamClient/files/15368970/log.txt)
[assert_20240519121359_14.txt (https://github.com/OpenSteamClient/OpenSteamClient/files/15368972/assert_20240519121359_14.txt)

Any idea on what to do? Maybe I am missing some files? There's this line
`dlmopen steamui.so failed: steamui.so: cannot open shared object file: No such file or directory`
that I think may be useful, but I have no clue on where to place steamui.so

**Comment by Rosentti** [comment]
Keeping this open, this might affect the C# remake as well.
The C++/Qt version is unmaintained. 
As for the issue:
Do you have a crash dump to send?
If you're using KDE, you might find it from "Crashed Processes Viewer", otherwise you might need to use coredumpctl.
The steamui.so message doesn't really mean anything.

**Comment by Linerd4** [comment]
> As for the issue: Do you have a crash dump to send? 
[assert_20240519185506_13.txt](https://github.com/OpenSteamClient/OpenSteamClient/files/15370139/assert_20240519185506_13.txt)
I hope this is the right file, I also got this from /var/lib/systemd/coredump:
[core.opensteam.1000.697fdc19c11444978617697dfbfaad90.6506.1716113232000000.txt](https://github.com/OpenSteamClient/OpenSteamClient/files/15370145/core.opensteam.1000.697fdc19c11444978617697dfbfaad90.6506.1716113232000000.txt)
You need to change the ".txt" extension to ".zst", because GitHub didn't let me upload that extension.

**Comment by Rosentti** [comment]
The systemd coredump is the right one.
I'm a bit new to dealing with coredumps, and it turns out I also need your opensteam executable?

**Comment by Linerd4** [comment]
> it turns out I also need your opensteam executable? 

[opensteam.txt](https://github.com/OpenSteamClient/OpenSteamClient/files/15370317/opensteam.txt)
Again, remove the ".txt" extension and you have the executable itself.

> -git packages on the AUR should always download from the master branch

Phew, good to know, I thought I compiled the dismissed qt version of opensteam

**Comment by Rosentti** [comment]
Oops, I thought I replied to this but the reply must not have sent.

The master branch contains the old version of the client. You did actually just get the old version. 
The new in development client isn't yet on the master branch and I've also deleted the AUR package since it was effectively deprecated (and didn't work, as you found out :D)
I'll make a new package once the remake is ready enough. For now, you can download the client from [GH actions](https://github.com/OpenSteamClient/OpenSteamClient/actions) or build it yourself

**Comment by Linerd4** [comment]
Well, here again for another problem! :)
I downloaded the client from GH actions as you said, I let it download all the stuff and then I got this message:
![2024-06-07_21-59-52-screenshot](https://github.com/OpenSteamClient/OpenSteamClient/assets/68269934/26450628-e7cd-4918-bf27-08ad7b2df277)

Source text here if it's of any use:

**OpenSteamClient has encountered a fatal exception. Exception message: This build has not been compiled with support for linux-x64. Please rebuild or try another OS. 
Alternatively, if you're running on 64-bit Windows, 64-bit Linux or 64-bit MacOS file an issue if this is a release build.**

System.NotSupportedException: This build has not been compiled with support for linux-x64. Please rebuild or try another OS. 
Alternatively, if you're running on 64-bit Windows, 64-bit Linux or 64-bit MacOS file an issue if this is a release build.
   at OpenSteamworks.Client.Startup.Bootstrapper.CopyOpensteamFiles(IExtendedProgress`1 progressHandler) in /home/runner/work/OpenSteamClient/OpenSteamClient/OpenSteamworks.Client/Startup/Bootstrapper.cs:line 987
   at OpenSteamworks.Client.Startup.Bootstrapper.RunBootstrap(Action`2 msgBoxProvider) in /home/runner/work/OpenSteamClient/OpenSteamClient/OpenSteamworks.Client/Startup/Bootstrapper.cs:line 360
   at OpenSteamClient.AvaloniaApp.OnFrameworkInitializationCompleted() in /home/runner/work/OpenSteamClient/OpenSteamClient/OpenSteamClient/AvaloniaApp.axaml.cs:line 79
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Avalonia.Threading.SendOrPostCallbackDispatcherOperation.InvokeCore()
   at Avalonia.Threading.DispatcherOperation.Execute()
   at Avalonia.Threading.Dispatcher.ExecuteJob(DispatcherOperation job)
   at Avalonia.Threading.Dispatcher.ExecuteJobsCore(Boolean fromExplicitBackgroundProcessingCallback)
   at Avalonia.Threading.Dispatcher.Signaled()
   at Avalonia.X11.X11PlatformThreading.CheckSignaled()
   at Avalonia.X11.X11PlatformThreading.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.DispatcherFrame.Run(IControlledDispatcherImpl impl)
   at Avalonia.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, ShutdownMode shutdownMode)
   at OpenSteamClient.Program.Main(String[] args) in /home/runner/work/OpenSteamClient/OpenSteamClient/OpenSteamClient/Program.cs:line 37

But this isn't a release build, so I guess this isn't of any interest. You may close this issue.
And thanks for helping!

**Comment by Rosentti** [comment]
Interesting. That shouldn't happen as of an update I did recently. I'll investigate tomorrow and report back. You sure you got the newest build?

**Comment by Linerd4** [comment]
Yes, I downloaded the build here:

https://github.com/OpenSteamClient/OpenSteamClient/actions/runs/9400351587

I unzipped, opened the terminal, launched "./OpenSteamClient", it downloaded a big bunch of stuff, and after a while I got that error.
Do you need any additional info?

EDIT: I've seen the error I reported it's the same in here: https://github.com/OpenSteamClient/OpenSteamClient/issues/48#issuecomment-2155802350

**Comment by Rosentti** [comment]
I've pushed a fix for the steamserviced issue, please retest

**Comment by Linerd4** [comment]
Now it works. Though when I got into the login section, and I've inserted my credentials, it tells me: Invalid Password.
I've checked the password by logging into Steam by browser: the password is the same and I managed to login.

Anyways, I used the Steam mobile app to login on OpenSteamClient, and it worked fine.
I'd say it's all fixed now.
