### ISSUE TITLE
qt6-webengine as an optional dep

### ISSUE THREAD

**Issue by SFort** [OpenSteamClient/OpenSteamClient#8]
please add an aur package that compiles with NOWEBVIEW and doesn't dep on qt6-webengine
or maybe an optional dep?
(i know next to nothing about C deps, so no clue if that's an unreasonable request)

thank you very much for the client.

**Comment by 20PercentRendered** [comment]
The webview is fully optional already. qt6-webengine is a build dep since I haven't yet figured out how I can detect it's install status from CMake. I'll look into this, aswell as improving the CMakeLists.

**Comment by 20PercentRendered** [comment]
I've made qt6-webengine now optional. I haven't updated the PKGBUILD on the AUR yet.
